[package]
name = "iv-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
strip = "debuginfo"

[dependencies]
